import re
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st
import io
import sys

notebook_content = """
{
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "**Asignatura:** Procesamiento de Datos\\n",
        "\\n",
        "**Carrera:** Tecnicatura Superior en Ciencias de  Datos e Inteligencia Artificial\\n",
        "\\n",
        "**Grupo 1:**\\n",
        "- Carabajal, Elba Julieta\\n",
        "- Bucci, Carlos Matias\\n",
        "- Schiavon, Leandro Nicolás\\n",
        "- Segovia Albarado, Nicolás Daniel\\n"
      ],
      "metadata": {
        "id": "6BmH0e9kjIAQ"
      },
      "id": "6BmH0e9kjIAQ"
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "-Rq7KxagiDx6"
      },
      "source": [
        "\\n",
        "## Sobre tratamiento de datos nulos\\n",
        "- Categóricas → `'Desconocido'` cuando faltan valores (MCAR)\\n",
        "- Numéricas → **mediana** (global) salvo que se pueda imputar por grupo (ej.: provincia)\\n",
        "- Reemplazos puntuales con **0** o **moda** cuando corresponda."
      ],
      "id": "-Rq7KxagiDx6"
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "q_cfrkEJiDx8",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "99065895-bd01-44a1-8be2-a59bc9df7adf"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\\u001b[?25l   \\u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\u001b[0m \\u001b[32m0.0/472.8 kB\\u001b[0m \\u001b[31m?\\u001b[0m eta \\u001b[36m-:--:--\\u001b[0m\\r\\u001b[2K   \\u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━\\u001b[0m\\u001b[91m╸\\u001b[0m\\u001b[90m━━━━━━━━━━━━\\u001b[0m \\u001b[32m327.7/472.8 kB\\u001b[0m \\u001b[31m9.6 MB/s\\u001b[0m eta \\u001b[36m0:00:01\\u001b[0m\\r\\u001b[2K   \\u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\u001b[0m \\u001b[32m472.8/472.8 kB\\u001b[0m \\u001b[31m9.4 MB/s\\u001b[0m eta \\u001b[36m0:00:00\\u001b[0m\\n",
            "\\u001b[?25h"
          ]
        }
      ],
      "source": [
        "# Instalar librerías necesarias (Colab)\\n",
        "!pip install python-pptx --quiet\\n",
        "import pandas as pd\\n",
        "import numpy as np\\n",
        "import matplotlib.pyplot as plt\\n",
        "from pathlib import Path\\n",
        "#from pptx import Presentation\\n",
        "#from pptx.util import Inches\\n",
        "#plt.rcParams['figure.figsize'] = (10,6)\\n",
        "#pd.set_option('display.max_columns', 80)\\n",
        "#pd.set_option('display.max_colwidth', 200)\\n"
      ],
      "id": "q_cfrkEJiDx8"
    },
    {
      "cell_type": "code",
      "source": [
        "#-----------------------------------------------\\n",
        "#    Cargar dataset (desde un CSV público)\\n",
        "#-----------------------------------------------\\n",
        "\\n",
        "path = \\"/content/base_da_2_con_faltantes.csv\\"\\n",
        "\\n",
        "df = pd.read_csv(path, sep=None, engine='python')\\n"
      ],
      "metadata": {
        "id": "j8h5t8Z_i06g"
      },
      "id": "j8h5t8Z_i06g",
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "1ap3zhngiDx9",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "5928b030-3329-4c50-f20b-fe6d82882a75"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\\n",
            "------> Dimensiones del dataset:   (8519, 9)\\n",
            "\\n",
            "\\n",
            "------> Información del dataset:  \\n",
            "<class 'pandas.core.frame.DataFrame'>\\n",
            "RangeIndex: 8519 entries, 0 to 8518\\n",
            "Data columns (total 9 columns):\\n",
            " #   Column                 Non-Null Count  Dtype  \\n",
            "---  ------                 --------------  -----  \\n",
            " 0   cod_provincia          8519 non-null   int64  \\n",
            " 1   provincia              8519 non-null   object \\n",
            " 2   cod_ncm_6d             8519 non-null   int64  \\n",
            " 3   ncm_6d                 8519 non-null   object \\n",
            " 4   seccion                8519 non-null   object \\n",
            " 5   tiene_vcr              8519 non-null   int64  \\n",
            " 6   centralidad            8223 non-null   float64\\n",
            " 7   complejidad_producto   8135 non-null   float64\\n",
            " 8   complejidad_provincia  6162 non-null   float64\\n",
            "dtypes: float64(3), int64(3), object(3)\\n",
            "memory usage: 599.1+ KB\\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "None"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\\n",
            "\\n",
            "------> Descripción del dataset <------\\n",
            "  \\n",
            "\\n",
            "--- Describe (numéricas) ---\\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "                        count           mean            std          min  \\\\n",
              "cod_provincia          8519.0      32.958094      31.373325      2.00000   \\\\n",
              "cod_ncm_6d             8519.0  517531.974528  292709.047538  10121.00000   \\\\n",
              "tiene_vcr              8519.0       0.186876       0.389835      0.00000   \\\\n",
              "centralidad            8223.0       0.168148       0.039433      0.01720   \\\\n",
              "complejidad_producto   8135.0      -0.089494       0.968992     -3.75520   \\\\n",
              "complejidad_provincia  6162.0      -0.349400       0.316403     -1.33322   \\\\n",
              "\\n",
              "                                25%            50%            75%  \\\\n",
              "cod_provincia               6.00000      14.000000      66.000000   \\\\n",
              "cod_ncm_6d             280440.00000  510529.000000  841280.000000   \\\\n",
              "tiene_vcr                   0.00000       0.000000       0.000000   \\\\n",
              "centralidad                 0.14350       0.174200       0.197950   \\\\n",
              "complejidad_producto       -0.78815       0.041600       0.645550   \\\\n",
              "complejidad_provincia      -0.36189      -0.334866      -0.165786   \\\\n",
              "\\n",
              "                                 max  \\n",
              "cod_provincia              94.000000  \\n",
              "cod_ncm_6d             999805.000000  \\n",
              "tiene_vcr                   1.000000  \\n",
              "centralidad                 0.252200  \\n",
              "complejidad_producto        2.626900  \\n",
              "complejidad_provincia       0.087869  "
            ],
            "text/html": [
              "\\n",
              "  <div id=\\"df-9c6cec4e-5e80-478d-a20b-7e5213aabb9f\\" class=\\"colab-df-container\\">\\n",
              "    <div>\\n",
              "<style scoped>\\n",
              "    .dataframe tbody tr th:only-of-type {\\n",
              "        vertical-align: middle;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe tbody tr th {\\n",
              "        vertical-align: top;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe thead th {\\n",
              "        text-align: right;\\n",
              "    }\\n",
              "</style>\\n",
              "<table border=\\"1\\" class=\\"dataframe\\">\\n",
              "  <thead>\\n",
              "    <tr style=\\"text-align: right;\\">\\n",
              "      <th></th>\\n",
              "      <th>count</th>\\n",
              "      <th>mean</th>\\n",
              "      <th>std</th>\\n",
              "      <th>min</th>\\n",
              "      <th>25%</th>\\n",
              "      <th>50%</th>\\n",
              "      <th>75%</th>\\n",
              "      <th>max</th>\\n",
              "    </tr>\\n",
              "  </thead>\\n",
              "  <tbody>\\n",
              "    <tr>\\n",
              "      <th>cod_provincia</th>\\n",
              "      <td>8519.0</td>\\n",
              "      <td>32.958094</td>\\n",
              "      <td>31.373325</td>\\n",
              "      <td>2.00000</td>\\n",
              "      <td>6.00000</td>\\n",
              "      <td>14.000000</td>\\n",
              "      <td>66.000000</td>\\n",
              "      <td>94.000000</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>cod_ncm_6d</th>\\n",
              "      <td>8519.0</td>\\n",
              "      <td>517531.974528</td>\\n",
              "      <td>292709.047538</td>\\n",
              "      <td>10121.00000</td>\\n",
              "      <td>280440.00000</td>\\n",
              "      <td>510529.000000</td>\\n",
              "      <td>841280.000000</td>\\n",
              "      <td>999805.000000</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>tiene_vcr</th>\\n",
              "      <td>8519.0</td>\\n",
              "      <td>0.186876</td>\\n",
              "      <td>0.389835</td>\\n",
              "      <td>0.00000</td>\\n",
              "      <td>0.00000</td>\\n",
              "      <td>0.000000</td>\\n",
              "      <td>0.000000</td>\\n",
              "      <td>1.000000</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>centralidad</th>\\n",
              "      <td>8223.0</td>\\n",
              "      <td>0.168148</td>\\n",
              "      <td>0.039433</td>\\n",
              "      <td>0.01720</td>\\n",
              "      <td>0.14350</td>\\n",
              "      <td>0.174200</td>\\n",
              "      <td>0.197950</td>\\n",
              "      <td>0.252200</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_producto</th>\\n",
              "      <td>8135.0</td>\\n",
              "      <td>-0.089494</td>\\n",
              "      <td>0.968992</td>\\n",
              "      <td>-3.75520</td>\\n",
              "      <td>-0.78815</td>\\n",
              "      <td>0.041600</td>\\n",
              "      <td>0.645550</td>\\n",
              "      <td>2.626900</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_provincia</th>\\n",
              "      <td>6162.0</td>\\n",
              "      <td>-0.349400</td>\\n",
              "      <td>0.316403</td>\\n",
              "      <td>-1.33322</td>\\n",
              "      <td>-0.36189</td>\\n",
              "      <td>-0.165786</td>\\n",
              "      <td>0.087869</td>\\n",
              "    </tr>\\n",
              "  </tbody>\\n",
              "</table>\\n",
              "</div>\\n",
              "    <div class=\\"colab-df-buttons\\">\\n",
              "\\n",
              "  <div class=\\"colab-df-container\\">\\n",
              "    <button class=\\"colab-df-convert\\" onclick=\\"convertToInteractive('df-9c6cec4e-5e80-478d-a20b-7e5213aabb9f')\\"\\n",
              "            title=\\"Convert this dataframe to an interactive table.\\"\\n",
              "            style=\\"display:none;\\">\\n",
              "\\n",
              "  <svg xmlns=\\"http://www.w3.org/2000/svg\\" height=\\"24px\\" viewBox=\\"0 -960 960 960\\">\\n",
              "    <path d=\\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\\"/>\\n",
              "  </svg>\\n",
              "    </button>\\n",
              "\\n",
              "  <style>\\n",
              "    .colab-df-container {\\n",
              "      display:flex;\\n",
              "      gap: 12px;\\n",
              "    }\\n",
              "\\n",
              "    .colab-df-convert {\\n",
              "      background-color: #E8F0FE;\\n",
              "      border: none;\\n",
              "      border-radius: 50%;\\n",
              "      cursor: pointer;\\n",
              "      display: none;\\n",
              "      fill: #1967D2;\\n",
              "      height: 32px;\\n",
              "      padding: 0 0 0 0;\\n",
              "      width: 32px;\\n",
              "    }\\n",
              "\\n",
              "    .colab-df-convert:hover {\\n",
              "      background-color: #E2EBFA;\\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\\n",
              "      fill: #174EA6;\\n",
              "    }\\n",
              "\\n",
              "    .colab-df-buttons div {\\n",
              "      margin-bottom: 4px;\\n",
              "    }\\n",
              "\\n",
              "    [theme=dark] .colab-df-convert {\\n",
              "      background-color: #3B4455;\\n",
              "      fill: #D2E3FC;\\n",
              "    }\\n",
              "\\n",
              "    [theme=dark] .colab-df-convert:hover {\\n",
              "      background-color: #434B5C;\\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\\n",
              "      fill: #FFFFFF;\\n",
              "    }\\n",
              "  </style>\\n",
              "\\n",
              "    <script>\\n",
              "      const buttonEl =\\n",
              "        document.querySelector('#df-9c6cec4e-5e80-478d-a20b-7e5213aabb9f button.colab-df-convert');\\n",
              "      buttonEl.style.display =\\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\\n",
              "\\n",
              "      async function convertToInteractive(key) {\\n",
              "        const element = document.querySelector('#df-9c6cec4e-5e80-478d-a20b-7e5213aabb9f');\\n",
              "        const dataTable =\\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\\n",
              "                                                    [key], {});\\n",
              "        if (!dataTable) return;\\n",
              "\\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\\n",
              "          '<a target=\\"_blank\\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\\n",
              "          + ' to learn more about interactive tables.';\\n",
              "        element.innerHTML = '';\\n",
              "        dataTable['output_type'] = 'display_data';\\n",
              "        await google.colab.output.renderOutput(dataTable, element);\\n",
              "        const docLink = document.createElement('div');\\n",
              "        docLink.innerHTML = docLinkHtml;\\n",
              "        element.appendChild(docLink);\\n",
              "      }\\n",
              "    </script>\\n",
              "  </div>\\n",
              "\\n",
              "\\n",
              "    <div id=\\"df-0579c817-3c59-41b5-a288-56548b1abdc7\\">\\n",
              "      <button class=\\"colab-df-quickchart\\" onclick=\\"quickchart('df-0579c817-3c59-41b5-a288-56548b1abdc7')\\"\\n",
              "                title=\\"Suggest charts\\"\\n",
              "                style=\\"display:none;\\">\\n",
              "\\n",
              "<svg xmlns=\\"http://www.w3.org/2000/svg\\" height=\\"24px\\"viewBox=\\"0 0 24 24\\"\\n",
              "     width=\\"24px\\">\\n",
              "    <g>\\n",
              "        <path d=\\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\\"/>\\n",
              "    </g>\\n",
              "</svg>\\n",
              "      </button>\\n",
              "\\n",
              "<style>\\n",
              "  .colab-df-quickchart {\\n",
              "      --bg-color: #E8F0FE;\\n",
              "      --fill-color: #1967D2;\\n",
              "      --hover-bg-color: #E2EBFA;\\n",
              "      --hover-fill-color: #174EA6;\\n",
              "      --disabled-fill-color: #AAA;\\n",
              "      --disabled-bg-color: #DDD;\\n",
              "  }\\n",
              "\\n",
              "  [theme=dark] .colab-df-quickchart {\\n",
              "      --bg-color: #3B4455;\\n",
              "      --fill-color: #D2E3FC;\\n",
              "      --hover-bg-color: #434B5C;\\n",
              "      --hover-fill-color: #FFFFFF;\\n",
              "      --disabled-bg-color: #3B4455;\\n",
              "      --disabled-fill-color: #666;\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-quickchart {\\n",
              "    background-color: var(--bg-color);\\n",
              "    border: none;\\n",
              "    border-radius: 50%;\\n",
              "    cursor: pointer;\\n",
              "    display: none;\\n",
              "    fill: var(--fill-color);\\n",
              "    height: 32px;\\n",
              "    padding: 0;\\n",
              "    width: 32px;\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-quickchart:hover {\\n",
              "    background-color: var(--hover-bg-color);\\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\\n",
              "    fill: var(--button-hover-fill-color);\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-quickchart-complete:disabled,\\n",
              "  .colab-df-quickchart-complete:disabled:hover {\\n",
              "    background-color: var(--disabled-bg-color);\\n",
              "    fill: var(--disabled-fill-color);\\n",
              "    box-shadow: none;\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-spinner {\\n",
              "    border: 2px solid var(--fill-color);\\n",
              "    border-color: transparent;\\n",
              "    border-bottom-color: var(--fill-color);\\n",
              "    animation:\\n",
              "      spin 1s steps(1) infinite;\\n",
              "  }\\n",
              "\\n",
              "  @keyframes spin {\\n",
              "    0% {\\n",
              "      border-color: transparent;\\n",
              "      border-bottom-color: var(--fill-color);\\n",
              "      border-left-color: var(--fill-color);\\n",
              "    }\\n",
              "    20% {\\n",
              "      border-color: transparent;\\n",
              "      border-left-color: var(--fill-color);\\n",
              "      border-top-color: var(--fill-color);\\n",
              "    }\\n",
              "    30% {\\n",
              "      border-color: transparent;\\n",
              "      border-left-color: var(--fill-color);\\n",
              "      border-top-color: var(--fill-color);\\n",
              "      border-right-color: var(--fill-color);\\n",
              "    }\\n",
              "    40% {\\n",
              "      border-color: transparent;\\n",
              "      border-right-color: var(--fill-color);\\n",
              "      border-top-color: var(--fill-color);\\n",
              "    }\\n",
              "    60% {\\n",
              "      border-color: transparent;\\n",
              "      border-right-color: var(--fill-color);\\n",
              "    }\\n",
              "    80% {\\n",
              "      border-color: transparent;\\n",
              "      border-right-color: var(--fill-color);\\n",
              "      border-bottom-color: var(--fill-color);\\n",
              "    }\\n",
              "    90% {\\n",
              "      border-color: transparent;\\n",
              "      border-bottom-color: var(--fill-color);\\n",
              "    }\\n",
              "  }\\n",
              "</style>\\n",
              "\\n",
              "      <script>\\n",
              "        async function quickchart(key) {\\n",
              "          const quickchartButtonEl =\\n",
              "            document.querySelector('#' + key + ' button');\\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\\n",
              "          try {\\n",
              "            const charts = await google.colab.kernel.invokeFunction(\\n",
              "                'suggestCharts', [key], {});\\n",
              "          } catch (error) {\\n",
              "            console.error('Error during call to suggestCharts:', error);\\n",
              "          }\\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\\n",
              "        }\\n",
              "        (() => {\\n",
              "          let quickchartButtonEl =\\n",
              "            document.querySelector('#df-109997b8-8bd9-474d-ab96-f40e70c75579 button');\\n",
              "          quickchartButtonEl.style.display =\\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\\n",
              "        })();\\n",
              "      </script>\\n",
              "    </div>\\n",
              "\\n",
              "    </div>\\n",
              "  </div>\\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\\n  \\"name\\": \\"display(pd\\",\\n  \\"rows\\": 9,\\n  \\"fields\\": [\\n    {\\n      \\"column\\": \\"nulos\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"number\\",\\n        \\"std\\": 771,\\n        \\"min\\": 0,\\n        \\"max\\": 2357,\\n        \\"num_unique_values\\": 4,\\n        \\"samples\\": [\\n          384,\\n          0,\\n          2357\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    },\\n    {\\n      \\"column\\": \\"%_nulos\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"number\\",\\n        \\"std\\": 9.060879433648319,\\n        \\"min\\": 0.0,\\n        \\"max\\": 27.67,\\n        \\"num_unique_values\\": 4,\\n        \\"samples\\": [\\n          4.51,\\n          0.0,\\n          27.67\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    }\\n  ]\\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#--------------------------------------------------\\n",
        "#       Limpieza y tratamiento de datos Nulos\\n",
        "#--------------------------------------------------\\n",
        "# Creamos copia para preservar original\\n",
        "df_clean = df.copy()\\n",
        "\\n",
        "# Definimos numéricas y de categorías\\n",
        "numeric_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()\\n",
        "cat_cols = df_clean.select_dtypes(include=['object','category']).columns.tolist()\\n",
        "\\n",
        "\\n",
        "# 1) Categóricas: sustituir nulos por 'Desconocido'\\n",
        "cat_con_nulos = [c for c in cat_cols if df_clean[c].isnull().sum()>0]\\n",
        "print('\\n--> Columnas categóricas con nulos: ', cat_con_nulos)\\n",
        "for c in cat_con_nulos:\\n",
        "    df_clean[c] = df_clean[c].fillna('Desconocido')\\n",
        "\\n",
        "# 2) Numéricas: sustituir por mediana global\\n",
        "num_con_nulos = [c for c in numeric_cols if df_clean[c].isnull().sum()>0]\\n",
        "print('\\n--> Columnas numéricas con nulos:', num_con_nulos)\\n",
        "for c in num_con_nulos:\\n",
        "    med = df_clean[c].median()\\n",
        "    df_clean[c] = df_clean[c].fillna(med)\\n",
        "\\n",
        "# 3) Ejemplo: si existe columna con 'prov' en su nombre, usar mediana por provincia para imputar una numérica (si aplica)\\n",
        "prov_candidates = [c for c in df_clean.columns if 'prov' in c.lower() or 'provincia' in c.lower()]\\n",
        "if prov_candidates and num_con_nulos:\\n",
        "    prov_col = prov_candidates[0]\\n",
        "    target_num = num_con_nulos[0]\\n",
        "    print(f'\\n--> Imputando {target_num} por mediana según {prov_col} (si hay nulos)')\\n",
        "    df_clean[target_num] = df_clean.groupby(prov_col)[target_num].transform(lambda x: x.fillna(x.median()))\\n",
        "\\n",
        "# 4) Reemplazo por moda/0 como ejemplos para columnas seleccionadas\\n",
        "if cat_cols:\\n",
        "    example_cat = cat_cols[0]\\n",
        "    moda = df_clean[example_cat].mode()[0]\\n",
        "    df_clean[example_cat] = df_clean[example_cat].fillna(moda)\\n",
        "    print(f'Reemplazado ejemplo categórica {example_cat} nulos por moda: {moda}')\\n",
        "if numeric_cols:\\n",
        "    example_num = numeric_cols[0]\\n",
        "    df_clean[example_num] = df_clean[example_num].fillna(0)\\n",
        "    print(f'Reemplazado ejemplo numérica {example_num} nulos por 0')\\n",
        "\\n",
        "print('\\n\\n--> Nulos restantes por columna (después):')\\n",
        "display(df_clean.isnull().sum().sort_values(ascending=False).head(60))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 557
        },
        "id": "E8lvqxGGnObM",
        "outputId": "30294e01-8f2c-4bb2-bf4f-c3fd0be5a9da"
      },
      "id": "E8lvqxGGnObM",
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\\n",
            "--> Columnas categóricas con nulos:  []\\n",
            "\\n",
            "--> Columnas numéricas con nulos: ['centralidad', 'complejidad_producto', 'complejidad_provincia']\\n",
            "\\n",
            "--> Imputando centralidad por mediana según cod_provincia (si hay nulos)\\n",
            "Reemplazado ejemplo categórica provincia nulos por moda: Buenos Aires\\n",
            "Reemplazado ejemplo numérica cod_provincia nulos por 0\\n",
            "\\n",
            "\\n",
            "--> Nulos restantes por columna (después):\\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "cod_provincia            0\\n",
              "provincia                0\\n",
              "cod_ncm_6d               0\\n",
              "ncm_6d                   0\\n",
              "seccion                  0\\n",
              "tiene_vcr                0\\n",
              "centralidad              0\\n",
              "complejidad_producto     0\\n",
              "complejidad_provincia    0\\n",
              "dtype: int64"
            ],
            "text/html": [
              "<div>\\n",
              "<style scoped>\\n",
              "    .dataframe tbody tr th:only-of-type {\\n",
              "        vertical-align: middle;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe tbody tr th {\\n",
              "        vertical-align: top;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe thead th {\\n",
              "        text-align: right;\\n",
              "    }\\n",
              "</style>\\n",
              "<table border=\\"1\\" class=\\"dataframe\\">\\n",
              "  <thead>\\n",
              "    <tr style=\\"text-align: right;\\">\\n",
              "      <th></th>\\n",
              "      <th>0</th>\\n",
              "    </tr>\\n",
              "  </thead>\\n",
              "  <tbody>\\n",
              "    <tr>\\n",
              "      <th>cod_provincia</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>provincia</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>cod_ncm_6d</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>ncm_6d</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>seccion</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>tiene_vcr</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>centralidad</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_producto</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_provincia</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "  </tbody>\\n",
              "</table>\\n",
              "</div><br><label><b>dtype:</b> int64</label>"
            ],
            "text/html": [
              "<div>\\n",
              "<style scoped>\\n",
              "    .dataframe tbody tr th:only-of-type {\\n",
              "        vertical-align: middle;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe tbody tr th {\\n",
              "        vertical-align: top;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe thead th {\\n",
              "        text-align: right;\\n",
              "    }\\n",
              "</style>\\n",
              "<table border=\\"1\\" class=\\"dataframe\\">\\n",
              "  <thead>\\n",
              "    <tr style=\\"text-align: right;\\">\\n",
              "      <th></th>\\n",
              "      <th>0</th>\\n",
              "    </tr>\\n",
              "  </thead>\\n",
              "  <tbody>\\n",
              "    <tr>\\n",
              "      <th>cod_provincia</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>provincia</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>cod_ncm_6d</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>ncm_6d</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>seccion</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>tiene_vcr</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>centralidad</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_producto</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_provincia</th>\\n",
              "      <td>0</td>\\n",
              "    </tr>\\n",
              "  </tbody>\\n",
              "</table>\\n",
              "</div><br><label><b>dtype:</b> int64</label>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 331
        },
        "id": "Yg08-BGZpUr2",
        "outputId": "de83e1b4-3e43-4245-c5b2-3a9b510f7d3d"
      },
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "                       nulos  %_nulos\\n",
              "cod_provincia              0      0.0\\n",
              "provincia                  0      0.0\\n",
              "cod_ncm_6d                 0      0.0\\n",
              "ncm_6d                     0      0.0\\n",
              "seccion                    0      0.0\\n",
              "tiene_vcr                  0      0.0\\n",
              "centralidad                0      0.0\\n",
              "complejidad_producto       0      0.0\\n",
              "complejidad_provincia      0      0.0"
            ],
            "text/html": [
              "\\n",
              "  <div id=\\"df-4b8fc141-1ef1-4ee7-9c70-9067c2eec4a9\\" class=\\"colab-df-container\\">\\n",
              "    <div>\\n",
              "<style scoped>\\n",
              "    .dataframe tbody tr th:only-of-type {\\n",
              "        vertical-align: middle;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe tbody tr th {\\n",
              "        vertical-align: top;\\n",
              "    }\\n",
              "\\n",
              "    .dataframe thead th {\\n",
              "        text-align: right;\\n",
              "    }\\n",
              "</style>\\n",
              "<table border=\\"1\\" class=\\"dataframe\\">\\n",
              "  <thead>\\n",
              "    <tr style=\\"text-align: right;\\">\\n",
              "      <th></th>\\n",
              "      <th>nulos</th>\\n",
              "      <th>%_nulos</th>\\n",
              "    </tr>\\n",
              "  </thead>\\n",
              "  <tbody>\\n",
              "    <tr>\\n",
              "      <th>cod_provincia</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>provincia</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>cod_ncm_6d</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>ncm_6d</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>seccion</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>tiene_vcr</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>centralidad</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_producto</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "    <tr>\\n",
              "      <th>complejidad_provincia</th>\\n",
              "      <td>0</td>\\n",
              "      <td>0.0</td>\\n",
              "    </tr>\\n",
              "  </tbody>\\n",
              "</table>\\n",
              "</div>\\n",
              "    <div class=\\"colab-df-buttons\\">\\n",
              "\\n",
              "  <div class=\\"colab-df-container\\">\\n",
              "    <button class=\\"colab-df-convert\\" onclick=\\"convertToInteractive('df-4b8fc141-1ef1-4ee7-9c70-9067c2eec4a9')\\"\\n",
              "            title=\\"Convert this dataframe to an interactive table.\\"\\n",
              "            style=\\"display:none;\\">\\n",
              "\\n",
              "  <svg xmlns=\\"http://www.w3.org/2000/svg\\" height=\\"24px\\" viewBox=\\"0 -960 960 960\\">\\n",
              "    <path d=\\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\\"/>\\n",
              "  </svg>\\n",
              "    </button>\\n",
              "\\n",
              "  <style>\\n",
              "    .colab-df-container {\\n",
              "      display:flex;\\n",
              "      gap: 12px;\\n",
              "    }\\n",
              "\\n",
              "    .colab-df-convert {\\n",
              "      background-color: #E8F0FE;\\n",
              "      border: none;\\n",
              "      border-radius: 50%;\\n",
              "      cursor: pointer;\\n",
              "      display: none;\\n",
              "      fill: #1967D2;\\n",
              "      height: 32px;\\n",
              "      padding: 0 0 0 0;\\n",
              "      width: 32px;\\n",
              "    }\\n",
              "\\n",
              "    .colab-df-convert:hover {\\n",
              "      background-color: #E2EBFA;\\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\\n",
              "      fill: #174EA6;\\n",
              "    }\\n",
              "\\n",
              "    .colab-df-buttons div {\\n",
              "      margin-bottom: 4px;\\n",
              "    }\\n",
              "\\n",
              "    [theme=dark] .colab-df-convert {\\n",
              "      background-color: #3B4455;\\n",
              "      fill: #D2E3FC;\\n",
              "    }\\n",
              "\\n",
              "    [theme=dark] .colab-df-convert:hover {\\n",
              "      background-color: #434B5C;\\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\\n",
              "      fill: #FFFFFF;\\n",
              "    }\\n",
              "  </style>\\n",
              "\\n",
              "    <script>\\n",
              "      const buttonEl =\\n",
              "        document.querySelector('#df-4b8fc141-1ef1-4ee7-9c70-9067c2eec4a9 button.colab-df-convert');\\n",
              "      buttonEl.style.display =\\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\\n",
              "\\n",
              "      async function convertToInteractive(key) {\\n",
              "        const element = document.querySelector('#df-4b8fc141-1ef1-4ee7-9c70-9067c2eec4a9');\\n",
              "        const dataTable =\\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\\n",
              "                                                    [key], {});\\n",
              "        if (!dataTable) return;\\n",
              "\\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\\n",
              "          '<a target=\\"_blank\\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\\n",
              "          + ' to learn more about interactive tables.';\\n",
              "        element.innerHTML = '';\\n",
              "        dataTable['output_type'] = 'display_data';\\n",
              "        await google.colab.output.renderOutput(dataTable, element);\\n",
              "        const docLink = document.createElement('div');\\n",
              "        docLink.innerHTML = docLinkHtml;\\n",
              "        element.appendChild(docLink);\\n",
              "      }\\n",
              "    </script>\\n",
              "  </div>\\n",
              "\\n",
              "\\n",
              "    <div id=\\"df-648487c9-7a0d-4252-befd-f8d54c92a378\\">\\n",
              "      <button class=\\"colab-df-quickchart\\" onclick=\\"quickchart('df-648487c9-7a0d-4252-befd-f8d54c92a378')\\"\\n",
              "                title=\\"Suggest charts\\"\\n",
              "                style=\\"display:none;\\">\\n",
              "\\n",
              "<svg xmlns=\\"http://www.w3.org/2000/svg\\" height=\\"24px\\"viewBox=\\"0 0 24 24\\"\\n",
              "     width=\\"24px\\">\\n",
              "    <g>\\n",
              "        <path d=\\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\\"/>\\n",
              "    </g>\\n",
              "</svg>\\n",
              "      </button>\\n",
              "\\n",
              "<style>\\n",
              "  .colab-df-quickchart {\\n",
              "      --bg-color: #E8F0FE;\\n",
              "      --fill-color: #1967D2;\\n",
              "      --hover-bg-color: #E2EBFA;\\n",
              "      --hover-fill-color: #174EA6;\\n",
              "      --disabled-fill-color: #AAA;\\n",
              "      --disabled-bg-color: #DDD;\\n",
              "  }\\n",
              "\\n",
              "  [theme=dark] .colab-df-quickchart {\\n",
              "      --bg-color: #3B4455;\\n",
              "      --fill-color: #D2E3FC;\\n",
              "      --hover-bg-color: #434B5C;\\n",
              "      --hover-fill-color: #FFFFFF;\\n",
              "      --disabled-bg-color: #3B4455;\\n",
              "      --disabled-fill-color: #666;\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-quickchart {\\n",
              "    background-color: var(--bg-color);\\n",
              "    border: none;\\n",
              "    border-radius: 50%;\\n",
              "    cursor: pointer;\\n",
              "    display: none;\\n",
              "    fill: var(--fill-color);\\n",
              "    height: 32px;\\n",
              "    padding: 0;\\n",
              "    width: 32px;\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-quickchart:hover {\\n",
              "    background-color: var(--hover-bg-color);\\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\\n",
              "    fill: var(--button-hover-fill-color);\\n",
              "  }\\n",
              "\\n",
              "  .colab-df-quickchart-complete:disabled,\\n",
              "  .colab-df-quickchart-complete:disabled:hover {\\n",
              "    background-color: var(--disabled-bg-color);\\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-648487c9-7a0d-4252-befd-f8d54c92a378 button');\n",
              "          quickchartButtonEl.style.display =\\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"display(pd\",\n  \"rows\": 9,\n  \"fields\": [\n    {\n      \"column\": \"nulos\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\
    {\n      \"column\": \"%_nulos\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0,\n        \"max\": 0.0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10"
    },
    "colab": {
      "provenance": []
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
"""

# Remove invalid control characters from notebook_content
# This addresses JSONDecodeError: Invalid control character
notebook_content = re.sub(r'[\x00-\x1f\x7f-\x9f]', '', notebook_content)

notebook = json.loads(notebook_content)

streamlit_code = []

# Add Streamlit import at the beginning
streamlit_code.append("import streamlit as st")
streamlit_code.append("import pandas as pd")
streamlit_code.append("import numpy as np")
streamlit_code.append("import matplotlib.pyplot as plt")
streamlit_code.append("import io")
streamlit_code.append("import sys")
streamlit_code.append("from pathlib import Path")
streamlit_code.append("")
streamlit_code.append("st.set_page_config(layout='wide')")
streamlit_code.append("st.title('Análisis de Datos de Exportaciones Argentinas')")
streamlit_code.append("")

# Function to load data with caching
streamlit_code.append("@st.cache_data")
streamlit_code.append("def load_data(path):")
streamlit_code.append("    df = pd.read_csv(path, sep=None, engine='python')")
streamlit_code.append("    return df")
streamlit_code.append("")

streamlit_code.append("df = load_data('base_da_2_con_faltantes.csv')")
streamlit_code.append("df_clean = df.copy()")
streamlit_code.append("")

for cell in notebook['cells']:
    if cell['cell_type'] == 'code':
        source_lines = cell['source']
        for line in source_lines:
            # Skip Colab specific installations
            if line.strip().startswith('!pip install'):
                continue
            # Replace Colab CSV path with local path
            if 'path = "/content/base_da_2_con_faltantes.csv"' in line:
                line = line.replace('path = "/content/base_da_2_con_faltantes.csv"', 'path = "base_da_2_con_faltantes.csv"')
            
            # Replace display() with st.dataframe() or st.write()
            if 'display(df.info())' in line:
                streamlit_code.append("st.subheader('Información del Dataset')")
                streamlit_code.append("buffer = io.StringIO()")
                streamlit_code.append("sys.stdout = buffer")
                streamlit_code.append("df.info()")
                streamlit_code.append("sys.stdout = sys.__stdout__")
                streamlit_code.append("st.text(buffer.getvalue())")
                continue
            if 'display(df.describe(include=[np.number]).T)' in line:
                streamlit_code.append("st.subheader('Descripción de Variables Numéricas')")
                streamlit_code.append("st.dataframe(df.describe(include=[np.number]).T)")
                continue
            if 'display(df.describe(include=["object"]).T)' in line:
                streamlit_code.append("st.subheader('Descripción de Variables Categóricas')")
                streamlit_code.append("st.dataframe(df.describe(include=['object']).T)")
                continue
            if 'display(df.head())' in line:
                streamlit_code.append("st.subheader('Primeras 5 filas del Dataset')")
                streamlit_code.append("st.dataframe(df.head())")
                continue
            if 'display(pd.concat([nulos, porc_nulos], axis=1, keys=["nulos", "%_nulos"]).head(60))' in line:
                streamlit_code.append("st.subheader('Valores Nulos por Columna')")
                streamlit_code.append("st.dataframe(pd.concat([nulos, porc_nulos], axis=1, keys=['nulos','%_nulos']).head(60))")
                continue
            if 'display(df_clean.isnull().sum().sort_values(ascending=False).head(60))' in line:
                streamlit_code.append("st.subheader('Nulos Restantes (Después de Limpieza)')")
                streamlit_code.append("st.dataframe(df_clean.isnull().sum().sort_values(ascending=False).head(60))")
                continue
            if 'display(df_clean.head())' in line:
                streamlit_code.append("st.subheader('Dataset Limpio (Primeras 5 filas)')")
                streamlit_code.append("st.dataframe(df_clean.head())")
                continue
            
            # Replace plt.show() with st.pyplot()
            if 'plt.show()' in line:
                streamlit_code.append("st.pyplot(plt.gcf())") # Get current figure and pass to streamlit
                streamlit_code.append("plt.close()") # Close the figure to free memory
                continue

            # Handle print statements
            if line.strip().startswith('print('):
                streamlit_code.append(line.replace('print(', 'st.write('))
                continue

            # General code lines
            streamlit_code.append(line)

final_streamlit_app_code = "\n".join(streamlit_code)

print(final_streamlit_app_code)